countries_by_world_region <-
structure(c("Afghanistan", "Albania", "Algeria", "Angola", "Argentina", 
"Australia", "Austria", "Bangladesh", "Belgium", "Bolivia", "Botswana", 
"Brazil", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", 
"Cameroon", "Canada", "Central African Republic", "Chad", "Chile", 
"China", "Colombia", "Costa Rica", "Croatia", "Cuba", "Czechia", 
"Denmark", "Dominican Republic", "Ecuador", "El Salvador", "England", 
"England and Wales", "Equatorial Guinea", "Estonia", "Eswatini", 
"Ethiopia", "Finland", "France", "Gambia", "Germany", "Greece", 
"Guatemala", "Guinea", "Haiti", "Honduras", "Hungary", "Iceland", 
"India", "Indonesia", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", 
"Japan", "Jordan", "Kazakhstan", "Kenya", "Kyrgyzstan", "Lebanon", 
"Malawi", "Mali", "Mauritania", "Mexico", "Moldova", "Mozambique", 
"Namibia", "Nepal", "Netherlands", "New Zealand", "Nigeria", 
"Northern Ireland", "Norway", "Pakistan", "Palestine", "Panama", 
"Paraguay", "Peru", "Philippines", "Portugal", "Romania", "Rwanda", 
"Scotland", "Senegal", "Sierra Leone", "Slovenia", "South Africa", 
"South Korea", "Spain", "Suriname", "Sweden", "Switzerland", 
"Taiwan", "Thailand", "Togo", "Turkey", "Uganda", "Ukraine", 
"United Kingdom", "Uruguay", "USA", "Venezuela", "Zambia", "Benin", 
"Maldives", "Montenegro", "Nicaragua", "Papua New Guinea", "Somalia", 
"Sudan", "Vietnam", "Asia", "Europe", "Africa", "Africa", "Latin America and the Caribbean", 
"Australia and New Zealand", "Europe", "Asia", "Europe", "Latin America and the Caribbean", 
"Africa", "Latin America and the Caribbean", "Europe", "Africa", 
"Africa", "Asia", "Africa", "Northern America", "Africa", "Africa", 
"Latin America and the Caribbean", "Asia", "Latin America and the Caribbean", 
"Latin America and the Caribbean", "Europe", "Latin America and the Caribbean", 
"Europe", "Europe", "Latin America and the Caribbean", "Latin America and the Caribbean", 
"Latin America and the Caribbean", "Europe", "Europe", "Africa", 
"Europe", "Africa", "Africa", "Europe", "Europe", "Africa", "Europe", 
"Europe", "Latin America and the Caribbean", "Latin America and the Caribbean", 
"Latin America and the Caribbean", "Latin America and the Caribbean", 
"Europe", "Europe", "Asia", "Asia", "Asia", "Europe", "Asia", 
"Europe", "Latin America and the Caribbean", "Asia", "Asia", 
"Asia", "Africa", "Asia", "Asia", "Africa", "Africa", "Africa", 
"Latin America and the Caribbean", "Europe", "Africa", "Africa", 
"Asia", "Europe", "Australia and New Zealand", "Africa", "Europe", 
"Europe", "Asia", "Asia", "Latin America and the Caribbean", 
"Latin America and the Caribbean", "Latin America and the Caribbean", 
"Asia", "Europe", "Europe", "Africa", "Europe", "Africa", "Africa", 
"Europe", "Africa", "Asia", "Europe", "Latin America and the Caribbean", 
"Europe", "Europe", "Asia", "Asia", "Africa", "Asia", "Africa", 
"Europe", "Europe", "Latin America and the Caribbean", "Northern America", 
"Latin America and the Caribbean", "Africa", "Afrika", "Asia", 
"Europe", "Latin America and the Caribbean", "Asia", "Africa", 
"Africa", "Asia"), .Dim = c(112L, 2L), .Dimnames = list(NULL, 
    c("new_countries_in_db", "wr_for_new_countries_in_db")))
